### PR TITLE
recipe/meta.yaml: quasi-nonsense commit to try retriggering CI

### PR DESCRIPTION
**Pull request by pkgw**
Not sure why Circle is failing on the most recent merged PR.

### CODE REVIEW

**Comment by isuruf** [comment]
Should this have multiple python builds on unix?

**Comment by pkgw** [comment]
Not on Unix ... only on Windows to get builds against the different versions of VC. I'll see if I can figure out how to set that up.

**Comment by isuruf** [comment]
If you are using `m2w64-toolchain`, then you don't need multiple builds

**Comment by pkgw** [comment]
@isuruf Like so?

```
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index 5456928..3c74e55 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -17,11 +17,6 @@ source:
 build:
   number: 0
   detect_binary_files_with_prefix: true
-  skip: true  # [not win and py<36]
-  features:
-    - vc9  # [win and py27]
-    - vc10  # [win and py34]
-    - vc14  # [win and py>=35]
 
 requirements:
   build:
@@ -34,9 +29,6 @@ requirements:
     - posix  # [win]
     - python  # [win]
     - toolchain
-    - vc 9  # [win and py27]
-    - vc 10  # [win and py34]
-    - vc 14  # [win and py>=35]
     - pthread-stubs
     - xorg-libx11 1.6.*
     - xorg-libxext 1.3.*
@@ -44,9 +36,6 @@ requirements:
     - xorg-libxt 1.1.*
     - xorg-util-macros
   run:
-    - vc 9  # [win and py27]
-    - vc 10  # [win and py34]
-    - vc 14  # [win and py>=35]
     - xorg-libx11 1.6.*
     - xorg-libxext 1.3.*
     - xorg-libxmu 1.1.*
```

**Comment by pkgw** [comment]
Sigh ... @isuruf do you have any insight as to why the CircleCI build is failing on the repo master branch? [Log here](https://circleci.com/gh/conda-forge/xorg-libxaw3d-feedstock/22). It seems like some kind of infrastructure problem but I don't know what to try besides rerendering.

**Pull request merged**
